/**
 * WeChat Address Book Service
 * WeChat-specific implementation of address book service
 */

import { AddressBookService, Address, ApiResponse } from '@vey/mini-common';

export class WeChatAddressBookService extends AddressBookService {
  /**
   * WeChat-specific HTTP request implementation
   */
  protected async request<T>(
    url: string,
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    data?: any
  ): Promise<ApiResponse<T>> {
    return new Promise((resolve) => {
      wx.request({
        url,
        method: method as any,
        data,
        header: {
          'content-type': 'application/json',
        },
        success: (res) => {
          resolve({
            success: res.statusCode === 200,
            data: res.data as T,
            error: res.statusCode !== 200 ? {
              code: `HTTP_${res.statusCode}`,
              message: res.data?.message || '请求失败',
            } : undefined,
          });
        },
        fail: (err) => {
          resolve({
            success: false,
            error: {
              code: 'NETWORK_ERROR',
              message: err.errMsg || '网络错误',
            },
          });
        },
      });
    });
  }
  
  /**
   * WeChat-specific: Use native address picker
   */
  async pickFromNative(): Promise<Address | null> {
    return new Promise((resolve) => {
      wx.chooseAddress({
        success: (res) => {
          // Convert WeChat address format to VEY Address format
          const address: Partial<Address> = {
            recipientName: res.userName,
            phoneNumber: res.telNumber,
            postalCode: res.postalCode,
            province: res.provinceName,
            city: res.cityName,
            district: res.countyName,
            street: res.detailInfo,
            countryCode: 'CN', // WeChat addresses are China by default
            pid: '', // Will be generated by backend
          };
          
          // Add to cloud address book
          this.addAddress(address as Omit<Address, 'pid'>)
            .then(resolve)
            .catch(() => resolve(null));
        },
        fail: () => {
          resolve(null);
        },
      });
    });
  }
  
  /**
   * WeChat-specific: Share address via WeChat
   */
  async shareViaWeChat(pid: string): Promise<boolean> {
    const address = await this.getAddressByPID(pid);
    if (!address) return false;
    
    return new Promise((resolve) => {
      wx.showShareMenu({
        withShareTicket: true,
        success: () => {
          // Share configuration would be set in onShareAppMessage
          wx.showToast({
            title: '共有メニューを開きました',
            icon: 'success',
          });
          resolve(true);
        },
        fail: () => {
          resolve(false);
        },
      });
    });
  }
  
  /**
   * WeChat-specific: Add address with loading UI
   */
  async addAddress(address: Omit<Address, 'pid'>): Promise<Address> {
    wx.showLoading({ title: '住所を追加中...' });
    
    try {
      const result = await super.addAddress(address);
      wx.hideLoading();
      wx.showToast({
        title: '住所を追加しました',
        icon: 'success',
      });
      return result;
    } catch (error: any) {
      wx.hideLoading();
      wx.showModal({
        title: 'エラー',
        content: error.message || '住所の追加に失敗しました',
        showCancel: false,
      });
      throw error;
    }
  }
}
