/**
 * Schema and file generators
 */

/**
 * Generate GraphQL schema content
 */
export function generateGraphQLSchema(): string {
  return `# Generated by veyform-sdk
# Vey Address GraphQL Schema

input AddressInput {
  recipient: String
  building: String
  floor: String
  room: String
  unit: String
  streetAddress: String
  district: String
  ward: String
  city: String
  province: String
  postalCode: String
  country: String!
}

type Address {
  id: ID!
  recipient: String
  building: String
  floor: String
  room: String
  unit: String
  streetAddress: String
  district: String
  ward: String
  city: String
  province: String
  postalCode: String
  country: String!
  formatted: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type ValidationResult {
  valid: Boolean!
  errors: [ValidationError!]!
  warnings: [ValidationWarning!]!
  normalized: Address
}

type ValidationError {
  field: String!
  code: String!
  message: String!
}

type ValidationWarning {
  field: String!
  code: String!
  message: String!
}

type CountryFormat {
  countryCode: String!
  countryName: String!
  requiredFields: [String!]!
  fieldOrder: [String!]!
  postalCodePattern: String
  postalCodeExample: String
}

type Query {
  address(id: ID!): Address
  validateAddress(input: AddressInput!, countryCode: String!): ValidationResult!
  countryFormat(countryCode: String!): CountryFormat
  countries: [CountryFormat!]!
}

type Mutation {
  createAddress(input: AddressInput!): Address!
  updateAddress(id: ID!, input: AddressInput!): Address!
  deleteAddress(id: ID!): Boolean!
}

scalar DateTime
`;
}

/**
 * Generate gRPC proto file content
 */
export function generateProtoFile(): string {
  return `// Generated by veyform-sdk
syntax = "proto3";

package vey.address.v1;

service AddressService {
  rpc ValidateAddress(ValidateAddressRequest) returns (ValidateAddressResponse);
  rpc GetAddress(GetAddressRequest) returns (Address);
  rpc CreateAddress(CreateAddressRequest) returns (Address);
  rpc UpdateAddress(UpdateAddressRequest) returns (Address);
  rpc DeleteAddress(DeleteAddressRequest) returns (DeleteAddressResponse);
}

message AddressInput {
  string recipient = 1;
  string building = 2;
  string floor = 3;
  string room = 4;
  string unit = 5;
  string street_address = 6;
  string district = 7;
  string ward = 8;
  string city = 9;
  string province = 10;
  string postal_code = 11;
  string country = 12;
}

message Address {
  string id = 1;
  string recipient = 2;
  string building = 3;
  string floor = 4;
  string room = 5;
  string unit = 6;
  string street_address = 7;
  string district = 8;
  string ward = 9;
  string city = 10;
  string province = 11;
  string postal_code = 12;
  string country = 13;
  string formatted = 14;
}

message ValidationError {
  string field = 1;
  string code = 2;
  string message = 3;
}

message ValidateAddressRequest {
  AddressInput address = 1;
  string country_code = 2;
}

message ValidateAddressResponse {
  bool valid = 1;
  repeated ValidationError errors = 2;
  Address normalized = 3;
}

message GetAddressRequest {
  string id = 1;
}

message CreateAddressRequest {
  AddressInput address = 1;
}

message UpdateAddressRequest {
  string id = 1;
  AddressInput address = 2;
}

message DeleteAddressRequest {
  string id = 1;
}

message DeleteAddressResponse {
  bool success = 1;
}
`;
}
