/**
 * Alipay Address Book Service
 * Alipay-specific implementation of address book service
 */

import { AddressBookService, Address, ApiResponse } from '@vey/mini-common';

export class AlipayAddressBookService extends AddressBookService {
  /**
   * Alipay-specific HTTP request implementation
   */
  protected async request<T>(
    url: string,
    method: 'GET' | 'POST' | 'PUT' | 'DELETE',
    data?: any
  ): Promise<ApiResponse<T>> {
    return new Promise((resolve) => {
      my.request({
        url,
        method: method as any,
        data,
        headers: {
          'content-type': 'application/json',
        },
        success: (res: any) => {
          resolve({
            success: res.status === 200,
            data: res.data as T,
            error: res.status !== 200 ? {
              code: `HTTP_${res.status}`,
              message: res.data?.message || '请求失败',
            } : undefined,
          });
        },
        fail: (err: any) => {
          resolve({
            success: false,
            error: {
              code: 'NETWORK_ERROR',
              message: err.errorMessage || '网络错误',
            },
          });
        },
      });
    });
  }
  
  /**
   * Alipay-specific: Use native address picker (chooseAddress)
   */
  async pickFromNative(): Promise<Address | null> {
    return new Promise((resolve) => {
      my.chooseAddress({
        success: (res: any) => {
          // Convert Alipay address format to VEY Address format
          const address: Partial<Address> = {
            recipientName: res.fullname,
            phoneNumber: res.mobilePhone,
            province: res.provinceName,
            city: res.cityName,
            district: res.districtName,
            street: res.address,
            countryCode: 'CN', // Alipay addresses are China by default
            pid: '', // Will be generated by backend
          };
          
          // Add to cloud address book
          this.addAddress(address as Omit<Address, 'pid'>)
            .then(resolve)
            .catch(() => resolve(null));
        },
        fail: () => {
          resolve(null);
        },
      });
    });
  }
  
  /**
   * Alipay-specific: Share address via Alipay
   */
  async shareViaAlipay(pid: string): Promise<boolean> {
    const address = await this.getAddressByPID(pid);
    if (!address) return false;
    
    return new Promise((resolve) => {
      my.showSharePanel({
        title: '住所を共有',
        desc: `${address.recipientName}様の住所`,
        success: () => {
          my.showToast({
            content: '共有しました',
            type: 'success',
          });
          resolve(true);
        },
        fail: () => {
          resolve(false);
        },
      });
    });
  }
  
  /**
   * Alipay-specific: Add address with loading UI
   */
  async addAddress(address: Omit<Address, 'pid'>): Promise<Address> {
    my.showLoading({ content: '住所を追加中...' });
    
    try {
      const result = await super.addAddress(address);
      my.hideLoading();
      my.showToast({
        content: '住所を追加しました',
        type: 'success',
      });
      return result;
    } catch (error: any) {
      my.hideLoading();
      my.alert({
        title: 'エラー',
        content: error.message || '住所の追加に失敗しました',
      });
      throw error;
    }
  }
  
  /**
   * Alipay-specific: Get user's authorized address
   */
  async getAuthorizedAddress(): Promise<Address | null> {
    return new Promise((resolve) => {
      my.getAddress({
        success: (res: any) => {
          const address: Partial<Address> = {
            recipientName: res.fullname,
            phoneNumber: res.mobilePhone,
            province: res.provinceName,
            city: res.cityName,
            district: res.districtName,
            street: res.address,
            countryCode: 'CN',
            pid: '',
          };
          
          this.addAddress(address as Omit<Address, 'pid'>)
            .then(resolve)
            .catch(() => resolve(null));
        },
        fail: () => resolve(null),
      });
    });
  }
}
